import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [name, setName] = useState("name");
  const [roll, setRoll] = useState(false);
  useEffect(() => {
    setRoll(false);
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="absolute h-screen w-screen overflow-hidden">
          <div
            className={`flex flex-col bg-blue-400 h-screen overflow-hidden ${
              roll ? "animate-rollup -translate-y-full" : ""
            }`}
          >
            <div className="m-auto ">
              <div className="mt-32">Welcome to Capriconous World</div>
            </div>
            <div className="m-auto">
              <button
                className="border-black border-2 py-4 px-6 rounded-3xl hover:animate-rotateButton bg-gradient-to-r from-cyan-500 to-purple-600"
                onClick={() => setRoll(!roll)}
              >
                Get Started
              </button>
            </div>
          </div>
        </div>
        <div className="h-5 bg-red-300 mb-10">testing1</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div className="h-5 bg-red-300 my-10">testing</div>
        <div></div>
      </main>
    </>
  );
}
