import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";
import Header from "components/header";
import Profile from "src/assets/download.jpg";
import { RootState, AppDispatch, useDispatch } from "src/redux/store";
import { userAction } from "src/redux/slices/userSlice";
import { authAction } from "src/redux/slices/authSlices";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
// import { alegreya } from "src/utils/font";

export default function Home() {
  const router = useRouter();
  const dispatch: AppDispatch = useDispatch();
  const [name, setName] = useState("name");
  const [roll, setRoll] = useState(false);
  const cekRedux = useSelector((state: RootState) => state.auth);
  useEffect(() => {
    // dispatch(authAction.authLoginThunk({ email: "fail", password: "fail" }));
    // dispatch(userAction.getUserHistoryThunk(cekRedux.token))
    // .unwrap()
    // .then(() => {
    //   console.log("success");
    // })
    //   .catch((err) => {
    //     dispatch(authAction.authLoginThunk.rejected);
    //     console.log("error");
    //   });
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {/* <div className="absolute h-screen w-screen overflow-hidden">
          <div
            className={`flex flex-col bg-blue-400 h-screen overflow-hidden ${
              roll ? "animate-rollup -translate-y-full" : ""
            }`}
          >
            <div className="m-auto ">
              <div className="mt-32">Welcome to Capriconous World</div>
            </div>
            <div className="m-auto">
              <button
                className="border-black border-2 py-4 px-6 rounded-3xl hover:animate-rotateButton bg-gradient-to-r from-cyan-500 to-purple-600"
                onClick={() => setRoll(!roll)}
              >
                Get Started
              </button>
            </div>
          </div>
        </div> */}
        <article>
          <section className="h-screen flex">
            <section className="w-1/12"></section>
            <section className="flex flex-col p-10 w-8/12">
              <div
                className="text-white cursor-pointer"
                onClick={() => {
                  router.push("#down");
                }}
              >
                Hi, my name is
                <div
                  className={`transition-colors bg-gradient-to-tr from-primary-300/40 via-primary-300/40 to-primary-400/40
                  dark:from-primary-300 dark:to-primary-400 dark:bg-clip-text dark:text-transparent`}
                >
                  Zanuar Bagus Ramadhan.
                </div>
              </div>
              <div>
                I am a software engineer specializing in designing user
                interfaces and user experiences, for web and mobile
                applications.
              </div>
              <div>
                Currently i am working as a Front-End Engineer at PT Tricada
                Tritonik, Bandung
              </div>
            </section>
            <section className="w-1/12"></section>
          </section>
          <section className="w-screen flex justify-center items-center">
            <button
              id="down"
              onClick={async () => {
                try {
                  const getHistory = await dispatch(
                    userAction.getUserHistoryThunk(cekRedux.token)
                  );
                } catch (error) {
                  console.log(error);
                }
              }}
              className="p-10 "
            >
              Tes API
            </button>
          </section>
        </article>
      </main>
    </>
  );
}
